### PR TITLE
Some fixes, Ubuntu 14.04

### PR DESCRIPTION
**Pull request by kupferk**
When working with the module and Cloudera 5.3.1 I could not create databses, because hive wanted to create a database in the local file system instead of using hdfs. So I resurrected the hdfs_hostname parameter in order to use it for specifying the warehouse path. Currently this variable will probably be mandatory. Maybe this setting should be optional?

I also added Ubuntu 14.04 as a compatible system.

Plus I added a .gitignore file for ignoring the pkg folder created by "puppet module build".

Finally I increased the version.

### CODE REVIEW

**Comment by valtri** [comment]
Did you use hive module alone or with combination with hadoop module? I'm just curious why it was working on our site :-).

The "hdfs://${hive::hdfs_hostname}" part shouldn't be probably used, when hdfs_hostname is empty (but I can add new patch on top of this pull request).

**Comment by kupferk** [comment]
I am using it with your Hadoop module in combination razorsedge/cloudera module for setting up the Cloudera repositories.

I needed to insert the prefix "hdfs://${hive::hdfs_hostname}", otherwise I could not create new databases from a client (I didn't test on the Hive metastore server itself). Maybe that's a Cloudera specific thing or changed with Hive versions.

**Comment by valtri** [comment]
I see. Hive is looking for hadoop configuration (/etc/hadoop/conf/core-site.xml) for defaultFS value. When hadoop is not configured, hive will consider the path without URI prefix as the local path.

So, administrator could include 'hadoop::common::config' to configure hadoop core for Hive (or install any of Hadoop component). Or he could use the new hdfs_hostname parameter instead.

**Comment by kupferk** [comment]
Ah, thank you for the enlightment. Indeed the core-site.xml was empty on my hive server node. I'll change that by including 'hadoop::common::config' as you suggested.

**Pull request merged**
